### ISSUE TITLE
cannot find the cppsdk repository

### ISSUE THREAD

**Issue by cometzero** [WebPlatformForEmbedded/meta-wpe#146]
Hi,

During build, I cannot find the cppsdk from git://git@github.com/Metrological/cppsdk.git;protocol=ssh;branch=master

https://github.com/Metrological/cppsdk

Is the link obsoluted?

**Comment by psivasubramanian** [comment]
@cometzero : No, it's restricted.

**Comment by wouterlucas** [comment]
Hi @cometzero, these are still closed. Sorry about that, we should probably add this to a README. We're still upstreaming/open sourcing the CPP and Webbridge parts which should solve this.

You can remove them from the image for now and it should build with the open source WPELauncher until the new framework is ready.

For more info please see:
https://github.com/WebPlatformForEmbedded/meta-wpe/issues/130
https://github.com/WebPlatformForEmbedded/meta-wpe/issues/136

**Comment by cometzero** [comment]
@psivasubramanian @wouterlucas Okay. I'll remove it until it's valid. Thanks.
