### ISSUE TITLE
Westeros compositor With DRM backend have issues 

### ISSUE THREAD

**Issue by pavannandyala** [WebPlatformForEmbedded/meta-wpe#148]
ISSUE 1:
there are certain issues with drm backend. issue observed is when we run compositor from ssh terminal and launch the compositor as backgroud process and # exit the terminal. then compositor will automatically crash if we move the cursor or launch westeros_test application with that wayland display
in swapDRMBuffers()

bo= gbm_surface_lock_front_buffer(surface);  returns null when the make westeros compositor
 

0xb7376f56 in gbm_bo_get_handle () from /usr/lib/libgbm.so.1
(gdb) bt
#0  0xb7376f56 in gbm_bo_get_handle () from /usr/lib/libgbm.so.1
#1  0xb76e922d in swapDRMBuffers (nativeBuffer=0xb5f12e00)
    at /usr/src/debug/westeros-soc-drm/1.0+gitrAUTOINC+260cb694a2-r0/git/drm/westeros-gl/westeros-gl.c:499
#2  eglSwapBuffers (dpy=0xb5f12398, surface=0xb5f12e20)
    at /usr/src/debug/westeros-soc-drm/1.0+gitrAUTOINC+260cb694a2-r0/git/drm/westeros-gl/westeros-gl.c:206
#3  0xb6a85f1c in wstRendererUpdateScene (renderer=0xb5f008b8)
    at /usr/src/debug/westeros/1.0+gitrAUTOINC+260cb694a2-r0/git/westeros-render-gl.cpp:1555
#4  0xb76d9e93 in WstRendererUpdateScene (renderer=0xb5f008b8)
    at /usr/src/debug/westeros/1.0+gitrAUTOINC+260cb694a2-r0/git/westeros-render.cpp:169
#5  0xb76d225f in wstCompositorComposeFrame (frameTime=466980058, ctx=0x8056078)
    at /usr/src/debug/westeros/1.0+gitrAUTOINC+260cb694a2-r0/git/westeros-compositor.cpp:3161
#6  wstCompositorDisplayTimeOut (data=0x8056078)
    at /usr/src/debug/westeros/1.0+gitrAUTOINC+260cb694a2-r0/git/westeros-compositor.cpp:3208
#7  0xb7341a25 in ?? () from /usr/lib/libwayland-server.so.0
#8  0xb7341fb9 in wl_event_loop_dispatch () from /usr/lib/libwayland-server.so.0
#9  0xb7340974 in wl_display_run () from /usr/lib/libwayland-server.so.0
#10 0xb76d6578 in wstCompositorThread (arg=0x8056078)
    at /usr/src/debug/westeros/1.0+gitrAUTOINC+260cb694a2-r0/git/westeros-compositor.cpp:2803
#11 0xb75591b6 in ?? () from /lib/libpthread.so.0
#12 0xb74554ee in clone () from /lib/libc.so.6

Error Reproduction steps:

Step1:
try ssh to the box or device in which westeros-compositor is available

launch westeros compositor through command line terminal

mkdir -p /run/user/0/
chmod 0700 /run/user/0/
export XDG_RUNTIME_DIR=/run/user/0/
export LD_PRELOAD=/usr/lib/libwesteros_gl.so.0.0.0
westeros --renderer /usr/lib/libwesteros_render_gl.so.0.0.0 --display wayland-0 --enableCursor  &

exit the terminal

move the cursor in device then when it invokes gbm_surface_lock_front_buffer it retuns NULL

ISSUE 2:

Launch the compositor via Startup systemd script 

and move cursor or launch westeros_test application then compositor will crash

crash happens in same line as gbm_surface_lock_front_buffer(surface) is failing and returns

no buffer object

This issue can be reproduced in any platform

observed in Hikey Board, Dragonboard and qemux86 platform as well

**Comment by wouterlucas** [comment]
Saw that you've raised the issues at the correct project (Westeros in this case). Closing this issue.
