### ISSUE TITLE
WARNING: No recipes available for Gstreamer

### ISSUE THREAD

**Issue by samouds** [WebPlatformForEmbedded/meta-wpe#168]
Hello,

I am using the latest version of meta-wpe (https://github.com/WebPlatformForEmbedded/meta-wpe/commit/bb6d3bbf21cb071dbec227ebb69954b70b63c3e2)

But I get this error at build : 

```
WARNING: No recipes available for:
  /home/samoud/resin-wpe/base-image/build/../meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.12.3.bbappend
  /home/samoud/resin-wpe/base-image/build/../meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.12.3.bbappend
  /home/samoud/resin-wpe/base-image/build/../meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.12.3.bbappend
  /home/samoud/resin-wpe/base-image/build/../meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.12.3.bbappend
  /home/samoud/resin-wpe/base-image/build/../meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0_1.12.3.bbappend
```

I checked the path /home/samoud/resin-wpe/base-image/build/../meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.12.3.bbappend and it exists.

Any idea ?

**Comment by wouterlucas** [comment]
Which version of oe-core/yocto are you using to generate your build?

**Comment by samouds** [comment]
I am using the rocko branch

**Comment by wouterlucas** [comment]
And which branch are you using for poky / openembedded-core recipes? Or if you are using a custom distro check the gstreamer1 version, usually this happens if the version of gstreamer is older (or newer) then the bbappends that we provide in meta-wpe. Krogoth OE/Yocto comes with Gstreamer 1.12.x, hence the patches we provide on top of that.

However older releases of Yocto will come with older versions of gstreamer, like morty comes with gst 1.8.x, pyro 1.10.x, etc.

**Comment by samouds** [comment]
I'm using the rocko branch for : 

meta-raspberrypi
meta-openembedded
poky

and master for meta-wpe and that's it.

I thought you meant openembedded-core when you said oe-core/yocto that's the same no ?

**Comment by wouterlucas** [comment]
Yeah, wasn't sure if you're using poky or some custom distro. So poky rocko has Gstreamer 1.12.2: https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-multimedia/gstreamer?h=rocko

Please use our rocko branch, which has the 1.12.2 bbappends: 
https://github.com/WebPlatformForEmbedded/meta-wpe/tree/rocko/recipes-multimedia/gstreamer

Master has been aligned with upstream master poky, which is already on 1.12.3 :-)

**Comment by samouds** [comment]
And how about the last fix (https://github.com/WebPlatformForEmbedded/meta-wpe/commit/bb6d3bbf21cb071dbec227ebb69954b70b63c3e2), it's on the rocko branch too ?

**Comment by wouterlucas** [comment]
It is now: https://github.com/WebPlatformForEmbedded/meta-wpe/commit/f873ca9a09ea7b6c2960d7706cf0948f6b0dc6cf :)

**Comment by samouds** [comment]
It's working ! thanks a lot !
