### ISSUE TITLE
repo is not working "Permission denied (publickey)."

### ISSUE THREAD

**Issue by malouf-erfan** [WebPlatformForEmbedded/meta-wpe#171]
Steps:
repo init -u ssh://git@github.com/WebPlatformForEmbedded/meta-wpe.git -b master -m tools/manifests/rpi-yocto.xml

Result :

Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
Permission denied (publickey).
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by wouterlucas** [comment]
Please make sure GitHub knows who you are if you are going to check something out through SSH. This can be done by adding your public key to the GitHub user. 

Follow the steps layed out in https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/ and it should work fine!

**Comment by malouf-erfan** [comment]
Thanks for the quick response
