### ISSUE TITLE
INIT: Id "s0" respawning too fast: disabled for 5 minutes

### ISSUE THREAD

**Issue by fellowgeek** [WebPlatformForEmbedded/meta-wpe#187]
On Raspberry Pi, I keep seeing this message:

INIT: Id "s0" respawning too fast: disabled for 5 minutes

is there a way to get rid of this?

Thanks

**Comment by kraj** [comment]
Can you try enabling serial port and see if it still happens ?

set 

```
ENABLE_UART = "1" 
```

in local.conf and rebuild.

**Comment by hhromic** [comment]
Or, if you don't want a serial port console at all, just disable it by setting this variable to empty:

    SERIAL_CONSOLE = ""

Useful for RPI0/W.

**Comment by fellowgeek** [comment]
ENABLE_UART = "1"  fixed it, thanks

**Comment by r-pai** [comment]
ENABLE_UART = "1" fixed for me too.. Thanks
