### ISSUE TITLE
libepoxy patch fails

### ISSUE THREAD

**Issue by DWagenk** [WebPlatformForEmbedded/meta-wpe#197]
My yocto build failed, because it couldnt apply this patch: https://github.com/WebPlatformForEmbedded/meta-wpe/blob/master/recipes-graphics/libepoxy/libepoxy/0001_make_graphic_libs_configureble.patch

Seems that libepoxy source for this file has changed and I couldn't find where the recipies selected wich version to pick.

I got it working in my copy manually changing this patch file and recompiling, but am not to firm in yocto yet, so I won't submit it as a fix

**Comment by estobbart** [comment]
@DWagenk Same issue. What were your steps to resolve it?

**Comment by kraj** [comment]
libepoxy has been updated in master  see
http://git.openembedded.org/openembedded-core/commit/meta/recipes-graphics/libepoxy?id=b72154eccfbcc178a2c09c7c7d4cd0264d4cf0f6

this patch needed to be forward ported.
