### ISSUE TITLE
Change screen resolution on RPI3

### ISSUE THREAD

**Issue by markov00** [WebPlatformForEmbedded/meta-wpe#207]
Hi I'm having problems using WPE on my RPI3.
The resolution seems fixed to 1280 x 720 (detected via window.innerWidth, window.innerHeight) when I'm using the official RPI display of 800x480.
I tried adding the env variables `WPE_INIT_VIEW_HEIGHT` and `WPE_INIT_VIEW_WIDTH` without success.
I've followed your guide here for building https://github.com/WebPlatformForEmbedded/meta-wpe/wiki/Raspberry-PI using the latest master version of meta-oe  `f0a664f`, meta-raspberrypi `693f36d`, and meta-wpe `3ae8a47`

The console resolution is fine. I've played a simple gst-launch with a video and the resolution is fine. When starting WPE the resolution is the one 

Thanks

**Comment by hhromic** [comment]
Hi, if you are using the Westeros-backend, the resolution is hard-coded. However, you can use a module to change it dynamically. Check this comment: https://github.com/WebPlatformForEmbedded/meta-wpe/issues/172#issuecomment-354137423. If you are using the EGLFS-backend, then WPE should adapt automatically to the whatever native resolution you configured in `config.txt`.

**Comment by markov00** [comment]
I'm using westeros backend. I'm now baking the EGLFS image one, but I will for sure test also the westeros with the module.
Thanks
