### ISSUE TITLE
Error during fetching inspector resource files (Main.html)

### ISSUE THREAD

**Issue by imrehg** [WebPlatformForEmbedded/meta-wpe#211]
I'm using the `meta-wpe` layer from the current master (f9c5f17c5acf835fd3166f5b6ca069a4b1e01ac5), and building these packages:
```
wpebackend \
wpebackend-rdk \
wpeframework \
wpeframework-plugins \
wpewebkit \
wpewebkit-web-inspector-plugin \
```
When running WPE, the WebInspector page seems to work, and `Inspectable web views` lists one view. When clicking on that on the other hand, goes to `/Main.html?page=1` and it shows an error:

```
Error: 0, The resource at â/org/wpe/inspector/UserInterface/Main.htmlâ does not exist occurred during fetching inspector resource files.
```
Am I missing something that needs to be enabled in yocto or at runtime?

**Comment by wouterlucas** [comment]
Which browser did you use to open the webinspector? Some browser may have issues rendering the webinspector. 

For me Sarai and latest Chrome seem to handle it quite well.

**Comment by imrehg** [comment]
@wouterlucas tested with latest Chromium and Epiphany. The error is also in the WPE logs, so it does look much more on that side, not on the browser's side..

**Comment by wouterlucas** [comment]
Oh you're right, I was testing on wpe-20170728. With wpe-2.20 I get the same error, I'm not sure to what extend the webinspector is still present in 2.20. As they where planning to remove it upstream.

**Comment by imrehg** [comment]
Thanks for the feedback, that's interesting, and I wonder if there's a planned replacement of any kind if the inspector is removed....

It seems that in the current master the web inspector is running by default on port `9998`, even when none of the plugin is added, so I guess there are a couple of pieces that come together for a workable inspector.

**Comment by wouterlucas** [comment]
We should move this issue to the WPEWebKit repo, this is not a meta-wpe specific issue.
