### ISSUE TITLE
WPE Browser Crashing while running a webgl application created from Unity 3D

### ISSUE THREAD

**Issue by sushant51** [WebPlatformForEmbedded/meta-wpe#230]
WPE Browser crashes after some time and leads to reboot RPI3, while running a webgl application which is created from Unity 3D.
what could be the issue? Kindly help.

Hardware : RaspberryPi3

**Comment by wouterlucas** [comment]
Is this issue still valid? 

If so can you provide an sample image for us to try? Likely it is memory related, increasing the memory tolerances on WPE will help a lot.

You can edit the memory pressure in:
`/etc/WPEFramework/plugins/WebKitBrowser.json`

Change the following two values:
```
  "memoryprofile":"128m",
 "memorypressure":"databaseprocess:50m,networkprocess:100m,webprocess:300m,rpcprocess:50m",
```

Set the memory profile to e.g. 500m and the webprocess to 700 (if that's what you RPI has available) and try again.
