### ISSUE TITLE
Touch support - old WPEWebkit referenced by Yocto image

### ISSUE THREAD

**Issue by TomMettam** [WebPlatformForEmbedded/meta-wpe#238]
With the referenced build of WPEWebkit, touch support does not work:

https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/535

However, this has been fixed in master.

**Comment by wouterlucas** [comment]
We'll move to WPE 2.22 soon, picking this branch: https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/wpe-2.22 

I'd expect to push a recipe change for that within the next few days.

**Comment by wouterlucas** [comment]
FYI https://github.com/WebPlatformForEmbedded/meta-wpe/issues/224 to enable touch, please make sure virtual input disabled. Closing this one.
