### ISSUE TITLE
Invalid license separator error for Yocto

### ISSUE THREAD

**Issue by alvaropg** [WebPlatformForEmbedded/meta-wpe#242]
bitbake returns an error about the license format:

`WARNING: /home/alvaropg/work/toolchains/rpi-yocto/meta-wpe/recipes-wpe/wpebackend/wpebackend_0.1.bb: wpebackend: LICENSE value "BSD 3-Clause" has an invalid format - license names must be separated by the following characters to indicate the license selection: &|() 
WARNING: /home/alvaropg/work/toolchains/rpi-yocto/meta-wpe/recipes-wpe/wpebackend-rdk/wpebackend-rdk_0.1.bb: wpebackend-rdk: LICENSE value "BSD 3-Clause" has an invalid format - license names must be separated by the following characters to indicate the license selection: &|() 
WARNING: /home/alvaropg/work/toolchains/rpi-yocto/meta-wpe/recipes-wpe/wpebackend-mesa/wpebackend-mesa_0.1.bb: wpebackend-mesa: LICENSE value "BSD 2-Clause/3-Clause" has an invalid separator "2-Clause/3-Clause" that is not in the valid list of separators (&|() )`

The issue refers to: d657d580da06889a54cd842e2b7e5d039128781e

As @shiftee points in the commit comment (https://github.com/WebPlatformForEmbedded/meta-wpe/commit/d657d580da06889a54cd842e2b7e5d039128781e#commitcomment-30494911) there is a format description here: https://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#var-LICENSE

**Comment by wouterlucas** [comment]
Fixed with 19cc6b06e35f6296d473e38fa7ac21fbc022b482
