### ISSUE TITLE
Question: which branch is the most stable and up to date?

### ISSUE THREAD

**Issue by fellowgeek** [WebPlatformForEmbedded/meta-wpe#273]
Hi,

Which branch is the most stable and up to date?

Thanks

**Comment by wouterlucas** [comment]
Depends on what you want to do and with which device :-)

Krogoth and Morty are being actively maintained for older devices but are pretty stable, but they are still receiving a lot of backports. 

Master is getting frequent updates and does follow the latest wpe stuff. Every bump does get smoke tested on an RPI before going into Master. Thud is the last known stable from November.
