### ISSUE TITLE
Build failure: bluetooth/mgmt.h

### ISSUE THREAD

**Issue by TomMettam** [WebPlatformForEmbedded/meta-wpe#281]
It seems recent changes have broken the build:

<pre>/build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/wpeframework-plugins/3.0+gitAUTOINC+fe68b1113c-r1/git/Bluetooth/Bluetooth.h:8:10: fatal error: bluetooth/mgmt.h: No such file or directory
|  #include &lt;bluetooth/mgmt.h&gt;
|           ^~~~~~~~~~~~~~~~~~
| compilation terminated.
</pre>

**Comment by bramoosterhuis** [comment]
This is a known issue, you can either remove Bluetooth distro feature or switch off Bluetooth in the wpeframework-plugins_git.bb manually by deleting this line:https://github.com/WebPlatformForEmbedded/meta-wpe/blob/master/recipes-wpe/wpeframework/wpeframework-plugins_git.bb#L36

**Comment by TomMettam** [comment]
Is there another issue ticket for the problem?

**Comment by wouterlucas** [comment]
Temporarily disabled bluetooth on wpeframework-plugins for this. That header does not get installed in Yocto and we'll need to write a bbappend for that.
