### ISSUE TITLE
Widevine Netflix

### ISSUE THREAD

**Issue by mikeDonahoe** [WebPlatformForEmbedded/meta-wpe#291]
I was wondering if anyone has had any luck getting Netflix to work.  Currently, have Amazon Prime and other Widevine protected streams working on the iMX6.  However, Netflix always displays an error.  Is it possible to playback Netflix content via WPEFramework or is the closed plugin mentioned in https://github.com/WebPlatformForEmbedded/meta-wpe/issues/164 required?

**Comment by mikeDonahoe** [comment]
Error that is displayed.

![image](https://user-images.githubusercontent.com/6437324/54891066-1bbf2880-4e7a-11e9-9376-a7a9ed0d7756.png)

**Comment by petegriffin** [comment]
Have you tried updating the user agent that WPE is sending to report a newer version of Chrome (e.g. v73)?

**Comment by mikeDonahoe** [comment]
Yes, I did.  I actually took the user agent string from my Laptop, which is able to play Netflix.  I'm guessing Netflix is checking for something in addition to the user agent.

**Comment by cchsu23** [comment]
@mikeDonahoe  Hi I has the same problem with you, do you have solution?
