### ISSUE TITLE
rk3399 recipes

### ISSUE THREAD

**Issue by StuartIanNaylor** [WebPlatformForEmbedded/meta-wpe#298]
Just a request
I have tried the raspberry pi recipe and the fixed no scalable window thing is no that great.

I noticed collabora have been doing much with mali and wondered if more "rk3399" specific recipes could be included.
RockPi & RockPro64 ?

**Comment by kraj** [comment]
sure if there are specific needs for WPE then this is the place, otherwise BSP layers are appropriate place.

**Comment by StuartIanNaylor** [comment]
It is really BSP but just thought I would ask if there is a Rockpi BSP & Panfrost support?

**Comment by wouterlucas** [comment]
There is no direct support for RockPi, best is to see if you can get Wayland/Westeros to work or see if you can go the wpebackend-fdo route over at meta-webkit :)
