### ISSUE TITLE
LIC checksum is wrong at Krogoth branch

### ISSUE THREAD

**Issue by bozlo** [WebPlatformForEmbedded/meta-wpe#303]
LIC_FILES_CHKSUM = "file://LICENSE;md5=e3fc50a88d0a364313df4b21ef20c29e" in meta-wpe/recipes-wpe/wpeframework/wpeframework-ui_git.bb is wrong.
Should it be 3b83ef96387f14655fc854ddc3c6bd57.

**Comment by wouterlucas** [comment]
Is fixed with latest merge & updates.
