### ISSUE TITLE
WebKitBrowser does not start

### ISSUE THREAD

**Issue by TomMettam** [WebPlatformForEmbedded/meta-wpe#320]
Machine: `raspberrypi3`

Using a vanilla build with master, WebKitBrowser refuses to start.

[     429046 us] Activated plugin [WebKitBrowser]:[WebKitBrowser]
[     721496 us] Deactivated plugin [WebKitBrowser]:[WebKitBrowser]
[     931315 us] Activated plugin [WebKitBrowser]:[WebKitBrowser]
[    1195794 us] Deactivated plugin [WebKitBrowser]:[WebKitBrowser]
[    1405704 us] Activated plugin [WebKitBrowser]:[WebKitBrowser]
[    1706825 us] Deactivated plugin [WebKitBrowser]:[WebKitBrowser]
[    1914587 us] Activated plugin [WebKitBrowser]:[WebKitBrowser]
[    2187098 us] Deactivated plugin [WebKitBrowser]:[WebKitBrowser]

There's no other output in syslog.

local.conf:

```
DISTRO_FEATURES_remove_rpi = "x11"
DISTRO_FEATURES_remove_rpi = "wayland"
```

Command:

`bitbake wpe-eglfs-image`

**Comment by wouterlucas** [comment]
Hey Tom, 

It seems the wpebackend-rdk is misconfigured through the recipe for the EGLFS case.
Set `WPE_BACKEND` to `rpi` and should will start.

I've fixed the issue in the recipe but it comes a long a whole update of srvrecvs and more, so will take me some time to push out.

**Comment by TomMettam** [comment]
@wouterlucas  Thanks for your response. Unfortunately, no dice. This is the entirety of my local.conf (I tried to cut everything back to just what information appears on the front page of this repo):

```
DISTRO_FEATURES_remove_rpi = "x11"
DISTRO_FEATURES_remove_rpi = "wayland"

WPE_BACKEND = "rpi"
```

Is anything else required? `WPE_PLATFORM` maybe?

**Comment by wouterlucas** [comment]
No that should be alright. Platform might be needed to enable EGL for video playback. But I saw wpebackend-rdk did not have a backend set by default for RPI EGLFS. 

I’ll check it as part of all the updates. Will probably take a day or more to get that all sorted.

**Comment by TomMettam** [comment]
Thanks @wouterlucas, I appreciate your help! I've tried a raw image with meta-webkit and cog which also encounters egl issues. I'm desperately trying to get something recent running, but failing.

**Comment by wouterlucas** [comment]
Try adding https://github.com/WebPlatformForEmbedded/meta-wpe/pull/321

With that at least I got graphics again, will run a few more tests and see what else is needed.

**Comment by wouterlucas** [comment]
Merged in, should be fine now. Also try  https://github.com/WebPlatformForEmbedded/meta-wpe/pull/323 for the latest Gstreamer 1.16 bumps.

With that 1080p graphics + video works fine for me on RPI3 EGLFS.
