### ISSUE TITLE
yocto build recipe "wpe-westeros-image" for raspberrypi3-64 fails, as the task 'wpeframework do_compile' is causing an error.

### ISSUE THREAD

**Issue by thadivaka-gopikrishna** [WebPlatformForEmbedded/meta-wpe#353]
Function failed: do_compile (log file is located at /home/gopi/my-yocto-project/build-toaster-3/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/temp/log.do_compile.8606)

[bblayers.conf.txt](https://github.com/WebPlatformForEmbedded/meta-wpe/files/3583594/bblayers.conf.txt)
[local.conf.txt](https://github.com/WebPlatformForEmbedded/meta-wpe/files/3583595/local.conf.txt)

[log.do_compile.8606.txt](https://github.com/WebPlatformForEmbedded/meta-wpe/files/3583620/log.do_compile.8606.txt)

**Comment by psivasubramanian** [comment]
Hi @thadivaka-gopikrishna, 
This issue is fixed in Thunder/WPEFramework commit https://github.com/WebPlatformForEmbedded/Thunder/commit/17d737fc6ceb6946a6d89751192575515556737b, but waiting for revision bump to happen in wpeframework recipe.
