### ISSUE TITLE
 Which backend for imx7dsabresd ( NXP MCIMX7 Sabre Board) in fullscreen mode 

### ISSUE THREAD

**Issue by fberndl** [WebPlatformForEmbedded/meta-wpe#382]
Hi,
we want to evaluate performance of the webkit running on imx7dsabresd on the NXP Sabre board.

-     We want to launch an website in fullscreen mode using the hdmi port.
-     This board does not support any hw accelleration.

Which backend and configuration should we choose. I read the wiki but I still don't know.

Thanks a lot

**Comment by wouterlucas** [comment]
There is not a lot of focus on IMX boards from my end, so I wish I could help. Have you visited our friends over at meta-webkit? I believe they do spend more time with IMX boards.
