### ISSUE TITLE
curl support required in meta-wpe

### ISSUE THREAD

**Issue by vkanupuru** [WebPlatformForEmbedded/meta-wpe#386]
curl support required in meta-wpe thunder

**Comment by wouterlucas** [comment]
okay what are you building that requires curl support?

**Comment by vkanupuru** [comment]
Basically we are trying to scan and pair bluetooth remote control device

**Comment by wouterlucas** [comment]
So do you need curl to be on your command line or do you have a build issue? 
Because adding curl to your image has nothing to do with meta-wpe, you can just add curl to your IMAGE_INSTALL in local.conf.

Also the recent Thunder UI includes Bluetooth support for scanning and pairing.

**Comment by vkanupuru** [comment]
ok thanks wouter
