### ISSUE TITLE
wpeFramework doesn't compile with glibc 2.31

### ISSUE THREAD

**Issue by pierreinglebert** [WebPlatformForEmbedded/meta-wpe#404]
As openembedded-core [now provides glibc 2.31](https://github.com/openembedded/openembedded-core/commit/ccb374c279b260b1fd3460f6bfd1567240816055), wpeframework doesn't compile anymore due to `stime()` being removed. A [fix is already on the master branch](https://github.com/WebPlatformForEmbedded/Thunder/commit/76269000542f3d211ece4a28680d9b2428214eac) of wpeframework but the version in meta-wpe is older.

**Comment by wouterlucas** [comment]
I'll prepare an update of the packages in master today.

**Comment by moorthy-bs** [comment]
@wouterlucas , This can be closed
